### ISSUE TITLE
Panic in newStartQuery

### ISSUE THREAD

**Issue by jacohend** [rethinkdb/rethinkdb-go#163]
This could just be because I'm a go noob, but I'm having issues in cases where other demos seem to work. I have a table called "users" with 1 primary key, "id". The Person test in example_query_select_test.go works fine when I put the query in main(), but fails inside the http handler. However, I see other demos, like the ToDo demo, doing this just fine. 

Rethink 1.16.2, Ubuntu 14.10 package
gorethink was checked out from master on Friday

```
goroutine 5 [running]:
net/http.func·009()
    /usr/lib/go/src/pkg/net/http/server.go:1093 +0xae
runtime.panic(0x6bcd80, 0xa68ec8)
    /usr/lib/go/src/pkg/runtime/panic.c:248 +0x106
github.com/dancannon/gorethink.newStartQuery(0x0, 0x7135c0, 0x6, 0x3800000000, 0x0, ...)
    /home/jacob/go/src/github.com/dancannon/gorethink/query.go:264 +0x1a3
github.com/dancannon/gorethink.Term.Run(0x7135c0, 0x6, 0x3800000000, 0x0, 0x0, ...)
    /home/jacob/go/src/github.com/dancannon/gorethink/query.go:195 +0x9f
github.com/dancannon/gorethink.Term.RunWrite(0x7135c0, 0x6, 0x3800000000, 0x0, 0x0, ...)
    /home/jacob/go/src/github.com/dancannon/gorethink/query.go:207 +0x92
```

The bottom of this stacktrace (not shown) just refers to the insert line in the http handler below. 

``` go
//File: server.go
package main

import (
    "fmt"
    "net/http"
    "github.com/gorilla/mux"
    r "github.com/dancannon/gorethink"
)

var session *r.Session
var dbname string = "test"
var port string = "28015"
var address string = "localhost"

type User struct {
    Id string `gorethink:"id, omitempty"`
    Username string `gorethink:"username"`
    Password string `gorethink:"password"`
    Email string `gorethink:"email"`
}

func register (w http.ResponseWriter, req *http.Request){
    _,inserterr := r.Table("users").Insert(User{
        Id: "1",
        Username: "hi",
        Password: "hi",
        Email:    "hi",
    }).RunWrite(session)
    if inserterr != nil{
        fmt.Fprintf(w, "Insert Error")
    }else{
        w.Header().Set("Server", "ReDB")
        w.WriteHeader(200)
    }
}

func main() {
    fmt.Println("Starting server...")
    session, err := r.Connect(r.ConnectOpts{
        Address: address + ":" + port,
        Database: dbname,
        MaxIdle: 10,
        MaxOpen: 10,
    })
    if err != nil {
        fmt.Println("cannot connect to db")
    }
    fmt.Println("connected to database")
    session.SetMaxOpenConns(5)
    fmt.Println("starting url router")
    mx := mux.NewRouter()
    mx.HandleFunc("/register", register)
    fmt.Println("registered routers")
    http.ListenAndServe(":8000", mx)
}
```

**Comment by dancannon** [comment]
Hi, it looks like your session is `nil` in the call to `Run`, probably because you are using the `:=` operator. Could you try the code below for connecting to the DB and let me know if that solves your issue. (The main difference is that err is defined before the call to `Connect`)

``` go
func main() {
    var err error

    fmt.Println("Starting server...")
    session, err = r.Connect(r.ConnectOpts{
        Address: address + ":" + port,
        Database: dbname,
        MaxIdle: 10,
        MaxOpen: 10,
    })
    if err != nil {
        fmt.Println("cannot connect to db")
    }
    fmt.Println("connected to database")
    session.SetMaxOpenConns(5)
    fmt.Println("starting url router")
    mx := mux.NewRouter()
    mx.HandleFunc("/register", register)
    fmt.Println("registered routers")
    http.ListenAndServe(":8000", mx)
}
```

**Comment by jacohend** [comment]
That solves it! Sorry for the noob question.

**Comment by dancannon** [comment]
Not a problem! Glad to help, if you have any more questions send me a message on https://gitter.im/dancannon/gorethink
