### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by importnil** [rethinkdb/rethinkdb-go#208]
Hi!

I'm coming from MySQL/PHP background, please excuse me if I'm doing something wrong.
For some reason I get invalid memory address error when trying to insert an item to DB. The connection is set in init() like this (yes I'm using gorethink as re):

``` go
var session *re.Session

func init() {
    var err error

    session, err := re.Connect(re.ConnectOpts{
        Address:  "127.0.0.1:28015",
        Database: "blog",
        MaxIdle:  1110,
        MaxOpen:  1110,
    })
    if err != nil {
        log.Fatalln(err.Error())
    }

    session.SetMaxOpenConns(115)
}
```

And the code to insert:

``` go
type PostTo struct {
    Id      string `gorethink:"id,omitempty"`
    Title   string `gorethink:"title"`
    Content string `gorethink:"content"`
}

data := PostTo{
    "1",
    "Sample Title",
    "Lorem Ipsum Dolor Sit Amet",
}

_, err := re.Table("articles").Insert(data).RunWrite(session)
if err != nil {
    fmt.Println(err)
}
```

RethinkDB version 2.0.4, Go is 1.3.3.

Full error log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x48dea9]

goroutine 16 [running]:
runtime.panic(0x71df40, 0x92ccb3)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/dancannon/gorethink.(*Session).newQuery(0x0, 0x75bda0, 0x6, 0x3800000000, 0x0, 0x0, 0xc20805e2d0, 0x2, 0x2, 0xc2080259e0, ...)
        /root/go/src/github.com/dancannon/gorethink/session.go:189 +0x79
github.com/dancannon/gorethink.Term.Run(0x75bda0, 0x6, 0x3800000000, 0x0, 0x0, 0xc20805e2d0, 0x2, 0x2, 0xc2080259e0, 0x0, ...)
        /root/go/src/github.com/dancannon/gorethink/query.go:215 +0xb2
github.com/dancannon/gorethink.Term.RunWrite(0x75bda0, 0x6, 0x3800000000, 0x0, 0x0, 0xc20805e2d0, 0x2, 0x2, 0xc2080259e0, 0x0, ...)
        /root/go/src/github.com/dancannon/gorethink/query.go:228 +0xb4
main.insertRecord()
        /root/go/src/github.com/vadimyer/sample/re.go:55 +0x175
main.main()
        /root/go/src/github.com/vadimyer/sample/re.go:106 +0x1e

goroutine 19 [finalizer wait]:
runtime.park(0x413690, 0x9317d0, 0x92fa29)
        /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x9317d0, 0x92fa29)
        /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
github.com/dancannon/gorethink.(*Pool).connectionOpener(0xc208060280)
        /root/go/src/github.com/dancannon/gorethink/pool.go:200 +0x48
created by github.com/dancannon/gorethink.NewPool
        /root/go/src/github.com/dancannon/gorethink/pool.go:69 +0x115

goroutine 21 [runnable]:
github.com/dancannon/gorethink.func·005()
        /root/go/src/github.com/dancannon/gorethink/node.go:47
created by github.com/dancannon/gorethink.newNode
        /root/go/src/github.com/dancannon/gorethink/node.go:57 +0x15d
exit status 2
```

**Comment by dancannon** [comment]
Hi, 

I cant immediately see anything wrong with the code you have posted for running the query however it is a little difficult to debug without the stack trace. Usually when a Go program panics and returns an error like the one you posted it prints a stack trace showing exactly what caused the error. Could you post this output? 

Thanks!

**Comment by importnil** [comment]
Thanks. So this is the first time for me trying to print a stack trace. Is this what you are looking for?

```
goroutine profile: total 6
1 @ 0x4bd20c 0x4bcfbb 0x4b9f63 0x401051 0x41155a 0x413d20
#       0x4bd20c        runtime/pprof.writeRuntimeProfile+0xcc  /usr/lib/go/src/pkg/runtime/pprof/pprof.go:540
#       0x4bcfbb        runtime/pprof.writeGoroutine+0x9b       /usr/lib/go/src/pkg/runtime/pprof/pprof.go:502
#       0x4b9f63        runtime/pprof.(*Profile).WriteTo+0xd3   /usr/lib/go/src/pkg/runtime/pprof/pprof.go:229
#       0x401051        main.main+0x81                          /root/go/src/github.com/vadimyer/sample/re.go:106
#       0x41155a        runtime.main+0x11a                      /usr/lib/go/src/pkg/runtime/proc.c:247

1 @ 0x404f66 0x40d0b3 0x413d20
#       0x404f66        runtime.notetsleepg+0x46        /usr/lib/go/src/pkg/runtime/lock_futex.c:198
#       0x40d0b3        runtime.MHeap_Scavenger+0xa3    /usr/lib/go/src/pkg/runtime/mheap.c:532

1 @ 0x413a89 0x413b0b 0x409d5a 0x413d20
#       0x409d5a        bgsweep+0x9a    /usr/lib/go/src/pkg/runtime/mgc0.c:1993

1 @ 0x413a89 0x413b0b 0x40b07f 0x413d20
#       0x40b07f        runfinq+0xcf    /usr/lib/go/src/pkg/runtime/mgc0.c:2644

1 @ 0x413a89 0x413b0b 0x41d258 0x41d6de 0x47ac98 0x413d20
#       0x41d258        chanrecv+0x1d8                                                  /usr/lib/go/src/pkg/runtime/chan.goc:298
#       0x41d6de        runtime.chanrecv2+0x3e                                          /usr/lib/go/src/pkg/runtime/chan.goc:358
#       0x47ac98        github.com/dancannon/gorethink.(*Pool).connectionOpener+0x48    /root/go/src/github.com/dancannon/gorethink/pool.go:200

1 @ 0x4916f0 0x413d20
#       0x4916f0        github.com/dancannon/gorethink.func·005+0x0     /root/go/src/github.com/dancannon/gorethink/node.go:47
```

**Comment by dancannon** [comment]
The full error log was exactly what I was looking for, so it looks like the session you are passing to RunWrite is `nil`, I believe this is because of how you are assigning the result of Connect to `session`. Because you are using `:=` it is not assigning your new session to the global `session` variable, try doing this instead `session, err = re.Connect`

Hope that helps, if not let me know.

**Comment by importnil** [comment]
Oh thanks Daniel. This was so simple! Will get used to it.

**Comment by Gitart** [comment]
type Mst map[string]interface{}                        // Map - string - interface
re.Table("articles").Insert(Mst{data}).RunWrite(session)

**Comment by dancannon** [comment]
@Gitart Are you having an issue with your code?

**Comment by Gitart** [comment]
No. Thanks. Sorry.  This my mistake.

**Comment by amogh-plivo** [comment]
I faced the same issue. Thanks.
