### ISSUE TITLE
Panic when calling .All

### ISSUE THREAD

**Issue by v9n** [rethinkdb/rethinkdb-go#233]
When I try to apply example on readme

```
     res, err := r.DB("rewl").Table("issues").Run(session)
     if err != nil {
       fmt.Fprintf(out, "Err: %v\n", err)
     }
    var rows []interface{}
    err = res.All(&rows)
```

And I got this. Did I do anything wrong?

```
2015/09/28 22:07:44 http: panic serving 127.0.0.1:50638: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc820100fd0, 0xaa4560, 0xc820078098)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1287 +0xb5
github.com/dancannon/gorethink.(*Session).newQuery(0x0, 0x49c7c0, 0x5, 0xf00000000, 0x0, 0x0, 0xc820101130, 0x2, 0x2, 0xc820142990, ...)
    /Users/kureikain/go/src/github.com/dancannon/gorethink/session.go:234 +0x87
github.com/dancannon/gorethink.Term.Run(0x49c7c0, 0x5, 0xf00000000, 0x0, 0x0, 0xc820101130, 0x2, 0x2, 0xc820142990, 0x0, ...)
    /Users/kureikain/go/src/github.com/dancannon/gorethink/query.go:235 +0xbb
main.IssuesHandler.func1(0xaa5930, 0xc820101080, 0xc8201462a0)
    /Users/kureikain/go/src/github.com/axcoto/rethink-weekly/main.go:90 +0x228
net/http.HandlerFunc.ServeHTTP(0x55fcc8, 0xaa5930, 0xc820101080, 0xc8201462a0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82007c410, 0xaa5930, 0xc820101080, 0xc8201462a0)
    /Users/kureikain/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.serverHandler.ServeHTTP(0xc8200987e0, 0xaa5930, 0xc820101080, 0xc8201462a0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820100fd0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1910 +0x3f6
2015/09/28 22:07:44 http: panic serving 127.0.0.1:50639: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc8201011e0, 0xaa4560, 0xc8200780a8)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1287 +0xb5
github.com/dancannon/gorethink.(*Session).newQuery(0x0, 0x49c7c0, 0x5, 0xf00000000, 0x0, 0x0, 0xc820101340, 0x2, 0x2, 0xc820142ba0, ...)
    /Users/kureikain/go/src/github.com/dancannon/gorethink/session.go:234 +0x87
github.com/dancannon/gorethink.Term.Run(0x49c7c0, 0x5, 0xf00000000, 0x0, 0x0, 0xc820101340, 0x2, 0x2, 0xc820142ba0, 0x0, ...)
    /Users/kureikain/go/src/github.com/dancannon/gorethink/query.go:235 +0xbb
main.IssuesHandler.func1(0xaa5930, 0xc820101290, 0xc820146380)
    /Users/kureikain/go/src/github.com/axcoto/rethink-weekly/main.go:90 +0x228
net/http.HandlerFunc.ServeHTTP(0x55fcc8, 0xaa5930, 0xc820101290, 0xc820146380)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82007c410, 0xaa5930, 0xc820101290, 0xc820146380)
    /Users/kureikain/go/src/github.com/gorilla/mux/mux.go:98 +0x29e
net/http.serverHandler.ServeHTTP(0xc8200987e0, 0xaa5930, 0xc820101290, 0xc820146380)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8201011e0)
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1910 +0x3f6
```

**Comment by v9n** [comment]
Close. I have been stupid
