### ISSUE TITLE
Panic if Pluck on not existing result

### ISSUE THREAD

**Issue by alehano** [rethinkdb/rethinkdb-go#241]
I try to Get(id).Pluck(pluck) but if id not exists, I get panic:
invalid memory address or nil pointer dereference

**Comment by dancannon** [comment]
Hey, sorry you are having this issue. Would it be possible to get the full stack trace and/or the rest of the code you are using?

Thanks

**Comment by alehano** [comment]
I use this helper to get data by id

``` go
func GetById(id string, res interface{}, table rdb.Term, pluck ...interface{}) error {
    var cur *rdb.Cursor
    var err error

    if len(pluck) > 0 {
        cur, err = table.Get(id).Pluck(pluck...).Run(SessRDB())
    } else {
        cur, err = table.Get(id).Run(SessRDB())
    }

    defer cur.Close()
    if err != nil {
        return err
    }
    err = cur.One(res)
    if err != nil {
        return err
    }
    return nil
}
```

And when I try this code, I got panic if there is no such id.
If id exists everything is ok.

``` go
    var res map[string]interface{}
    err := GetById("someFakeId", &res, gorethink.DB("mydb").Table("table"), "AccountId")
```

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x41d2fc7]

goroutine 14 [running]:
testing.func·006()
    /usr/local/go/src/testing/testing.go:441 +0x181
github.com/dancannon/gorethink.(*Cursor).Close(0x0, 0x0, 0x0)
    /Users/alehano/Development/go/src/github.com/dancannon/gorethink/cursor.go:98 +0x257
bitbucket.org/akhalyapin/optlist/sys/db.GetById(0x46aef70, 0x7, 0x4464f20, 0xc20802eb98, 0x465caf0, 0x5, 0xf00000000, 0x0, 0x0, 0xc208155130, ...)

...
```

**Comment by dancannon** [comment]
It appears that you are defering the `Close` call before checking the error so this call panics. Moving this after the check should fix your issue.

**Comment by alehano** [comment]
Yeah, you're right. 
Now I get error 

```
    Cannot perform pluck on a non-object non-sequence `null`. in:
        r.DB("test_main").Table("companies").Get("nothing").Pluck("AccountId")
```

Thanks.

**Comment by dancannon** [comment]
It might be worth using `Default`, for example:

```
r.DB("test_main").Table("companies").Get("nothing").Default(map[string]interface{}{}).Pluck("AccountId")
```

**Comment by alehano** [comment]
Cool! Thanks a lot.

**Comment by alehano** [comment]
But If I will return error before defer. It means that defer won't be called? So cursor won't be closed?
