### ISSUE TITLE
running multiple runwrites that return a error seems to be causing problems

### ISSUE THREAD

**Issue by thinkong** [rethinkdb/rethinkdb-go#251]
I have some code.. that used to work before i recently did an update on the  package.

the code was to Indexcreate("something").RunWrite(session) multiple times to enforce indexcreations...

this worked. until recently i did a go get -u 

now it keeps telling me panic: runtime error: invalid memory address or nil pointer dereference

is this working as intended?

**Comment by dancannon** [comment]
Hi thanks for the bug report, could you maybe post the full stack trace to help me debug this? Thanks.

**Comment by thinkong** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x6bed1d]
goroutine 1 [running]:
github.com/dancannon/gorethink.(*Cluster).GetNextNode(0xc08271a2a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/mygame/myserver/src/github.com/dancannon/gorethink/cluster.go:365 +0x14d
github.com/dancannon/gorethink.(*Cluster).Query(0xc08271a2a0, 0x1, 0x0, 0xc082273bc0, 0xc0820d5f50, 0x8ed960, 0xc0827f2c40, 0xc0820d5f50, 0x0, 0x0)
        D:/mygame/myserver/src/github.com/dancannon/gorethink/cluster.go:57 +0x40
github.com/dancannon/gorethink.(*Session).Query(0xc082006370, 0x1, 0x0, 0xc082273bc0, 0xc0820d5f50, 0x8ed960, 0xc0827f2c40, 0x0, 0x0, 0x0)
        D:/mygame/myserver/src/github.com/dancannon/gorethink/session.go:221 +0x12d
github.com/dancannon/gorethink.Term.Run(0xaaa1f0, 0xb, 0x4b00000000, 0x0, 0x0, 0xc08213e4d0, 0x2, 0x2, 0x0, 0x0, ...)
        D:/mygame/myserver/src/github.com/dancannon/gorethink/query.go:239 +0x192
github.com/dancannon/gorethink.Term.RunWrite(0xaaa1f0, 0xb, 0x4b00000000, 0x0, 0x0, 0xc08213e4d0, 0x2, 0x2, 0x0, 0x0, ...)
        D:/mygame/myserver/src/github.com/dancannon/gorethink/query.go:252 +0xb1
main/vendor/kbo.(*DataDB).connectToDB(0xd9c470, 0xc0828786c0)
        D:/mygame/myserver/src/main/vendor/kbo/dbstuff.go:115 +0x2426
main/vendor/kbo.init.4()
        D:/mygame/myserver/src/main/vendor/kbo/dbstuff.go:139 +0x12b
main/vendor/kbo.init()
        D:/mygame/myserver/src/main/vendor/kbo/staticDBFuncs.go:507 +0x113
main.init()
        D:/mygame/myserver/src/main/main.go:936 +0x6c

goroutine 8 [chan receive]:
github.com/hailocab/go-hostpool.(*epsilonGreedyHostPool).epsilonGreedyDecay(0xc082068120)
        D:/mygame/myserver/src/github.com/hailocab/go-hostpool/epsilon_greedy.go:88 +0x7e
created by github.com/hailocab/go-hostpool.NewEpsilonGreedy
        D:/mygame/myserver/src/github.com/hailocab/go-hostpool/epsilon_greedy.go:64 +0x32f
```

will this do? :D

**Comment by dancannon** [comment]
Perfect thanks, I will try to get that fixed after work this evening.

**Comment by dancannon** [comment]
Haha, ok so it turns out this was due to a bug in the go-hostpool that I added. Luckily it was a small change to fix the issue so the panic should now be gone.

Could you please run `go get -u ./...` again and test to be sure. Thanks

**Comment by thinkong** [comment]
yep i think that fixed it :+1:
