### ISSUE TITLE
crashing on restart of rethinkdb

### ISSUE THREAD

**Issue by gabeio** [rethinkdb/rethinkdb-go#276]
## How I am connecting:

current way to connect:

``` go
session, err := r.Connect(r.ConnectOpts{
    Address:  rethinkurl,
    Database: "test",
    MaxIdle:  1, // also tried 0
    MaxOpen:  40,
})
session.Use(os.Getenv("RETHINK_DB"))
if err != nil {
    log.Fatal(err)
}
sessionChan <- session
```
## The query

(though fairly sure this is not specifically needed.)

``` go
func getOneUser(username string, user interface{}, done chan error) {
    if !rethinkSession.IsConnected() {
        err = rethinkSession.Reconnect()
        if err != nil {
            log.Panic("getOneUser 1: ",err)
            done <- err
        }
    } else {
        log.Print("getOneUser is connected!")
    }
    cursor, err := r.Table("users").Filter(map[string]interface{}{
        "username": username,
    }).Run(rethinkSession)
    defer cursor.Close()
    if err != nil { // should I be checking for EOF here and just trying a restart?
        log.Panic("getOneUser 2:",err)
        done <- err
    } else {
        done <- cursor.One(user)
    }
}
```
## What I already tried:

when I restart the rethinkdb server (usually to update) gorethink doesn't reconnect it just crashes. I even tried adding a check to see if it is connected:

``` go
if !rethinkSession.IsConnected() {
    err = rethinkSession.Reconnect()
    if err != nil {
        log.Panic("getOneUser 1: ",err)
        done <- err
    }
} else {
    log.Print("getOneUser is connected!")
}
```

I did manage to force it to work with a temp fix by forcing a reconnect on EVERY QUERY:

I just feel like that's:
- not efficient
- not DRY
## Logs:

But I always get a broken pipe:

```
2016/02/29 00:33:44 getOneUser is connected!
2016/02/29 00:33:44 getOneUser 2: EOF
panic: getOneUser 2: EOF
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb2c48]

goroutine 49 [running]:
panic(0x4813b8, 0x1090a038)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x330
gopkg.in/dancannon/gorethink%2ev1.(*Cursor).Close(0x0, 0x0, 0x0)
    /Volumes/MacHDD/Users/gabeio/go/src/gopkg.in/dancannon/gorethink.v1/cursor.go:101 +0x38
panic(0x40da20, 0x1090b048)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x448
log.Panic(0x10b02f3c, 0x2, 0x2)
    /usr/local/Cellar/go/1.6/libexec/src/log/log.go:320 +0xa4
main.getOneUser(0x10a9f3e5, 0x6, 0x49e9f0, 0x10a31840, 0x10a442c0)
    /Volumes/MacHDD/Users/gabeio/repos/go/<repo>/database.go:157 +0x46c
created by main.GetPeeves
    /Volumes/MacHDD/Users/gabeio/repos/go/<repo>/peeves.go:21 +0x29c
```
## Steps to reproduce:
- start an app using rethinkdb
- restart the rethinkdb server
- have the app query anything

**Comment by dancannon** [comment]
Hi, thanks for the details bug report. I had a look at your code and tried to replicate the issue but I am still having some issues. Could this issue be due to the `log.Panic("getOneUser 1: ",err)`?

In my test I let the code run for a second and then restarted the database, as you can see after the database started again the queries started succeeding again after a few errors.

``` go
package main

import (
    "time"

    "github.com/Sirupsen/logrus"

    r "github.com/dancannon/gorethink"
)

func main() {
    r.SetVerbose(true)
    s, err := r.Connect(r.ConnectOpts{
        Address: "localhost:28015",
    })
    if err != nil {
        panic(err)
    }

    for {
        time.Sleep(time.Millisecond * 100)

        cursor, err := r.Expr("hello world").Run(s)
        defer cursor.Close()
        if err != nil {
            logrus.Errorf("Error received: %s", err)
            continue
        }

        var result string
        if err := cursor.One(&result); err != nil {
            logrus.Errorf("Error received: %s", err)
            continue
        }

        logrus.Info(result)
    }
}
```

```
DEBU[0000] Connected to node                             host=localhost:28015 id=localhost:28015
INFO[0000] hello world
INFO[0000] hello world
INFO[0000] hello world
INFO[0000] hello world
INFO[0000] hello world
INFO[0000] hello world
INFO[0000] hello world
INFO[0000] hello world
INFO[0000] hello world
INFO[0001] hello world
ERRO[0001] Error received: EOF
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0001] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0002] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0003] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0003] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0003] Error received: dial tcp [::1]:28015: getsockopt: connection refused
ERRO[0003] Error received: dial tcp [::1]:28015: getsockopt: connection refused
INFO[0003] hello world
INFO[0003] hello world
INFO[0003] hello world
INFO[0003] hello world
INFO[0003] hello world
INFO[0003] hello world
INFO[0004] hello world
INFO[0004] hello world
INFO[0004] hello world
INFO[0004] hello world
INFO[0004] hello world
```

**Comment by gabeio** [comment]
Okay this is embarrassing... I thought I had debugged enough, apparently not. I found my dereference of a nil pointer. Sorry for the scare & the wasted time. (It was right after the call of the function I listed.)

**Comment by gabeio** [comment]
continued (maybe):

panic of dereference:

```
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:426 (0x43d639)
    gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:45 (0x43bce9)
    panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x4523aa)
    sigpanic: panicmem()
/home/gabeio/go/src/gopkg.in/dancannon/gorethink.v1/cursor.go:101 (0x4b8fe3)
    (*Cursor).Close: c.mu.Lock()
/usr/local/go/src/runtime/asm_amd64.s:472 (0x46c77e)
    call32: CALLFN(·call32, 32)
/usr/local/go/src/runtime/panic.go:426 (0x43d639)
    gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:45 (0x43bce9)
    panicmem: panic(memoryError)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x4523aa)
    sigpanic: panicmem()
/home/gabeio/go/src/gopkg.in/dancannon/gorethink.v1/cursor.go:370 (0x4ba9c3)
    (*Cursor).IsNil: c.mu.RLock()
/home/gabeio/3bs/database.go:239 (0x40459d)
    getPoints: if cursor.IsNil() {      <- note this is only checking if it's nil not even accessing anything
/home/gabeio/3bs/database.go:227 (0x404106)
    housePoints: Hufflepuff: getPoints("hufflepuff"),
/home/gabeio/3bs/routes.go:230 (0x40cfb7)
    points: housePoints(),
/home/gabeio/go/src/github.com/gin-gonic/gin/context.go:97 (0x51581a)
    (*Context).Next: c.handlers[c.index](c)
/home/gabeio/go/src/github.com/gin-gonic/gin/recovery.go:45 (0x527eb1)
    RecoveryWithWriter.func1: c.Next()
/home/gabeio/go/src/github.com/gin-gonic/gin/context.go:97 (0x51581a)
    (*Context).Next: c.handlers[c.index](c)
/home/gabeio/go/src/github.com/gin-gonic/gin/logger.go:66 (0x52714a)
    LoggerWithWriter.func1: c.Next()
/home/gabeio/go/src/github.com/gin-gonic/gin/context.go:97 (0x51581a)
    (*Context).Next: c.handlers[c.index](c)
/home/gabeio/go/src/github.com/gin-gonic/gin/gin.go:284 (0x51c472)
    (*Engine).handleHTTPRequest: context.Next()
/home/gabeio/go/src/github.com/gin-gonic/gin/gin.go:265 (0x51c0a7)
    (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2081 (0x57fade)
    serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1472 (0x57c38e)
    (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1998 (0x46ee51)
    goexit: BYTE    $0x90   // NOP
```

different function this time:

``` go
func getPoints(house string) int {
    cursor, err := r.Table("points").Filter(map[string]interface{}{
        "house": house,
    }).Field("points").Sum().Run(rethinkSession)
    defer cursor.Close()
    if cursor.IsNil() {
        return 0
    }
    var points int
    err = cursor.One(&points)
    if err != nil {
        log.Print(err)
        return 0
    } else {
        return points
    }
}
```

reproduce:
- stop instead of restart one of 2 servers

**Comment by gabeio** [comment]
digging further:

``` go
func getPoints(house string) int {
    sleep := 0
    for {
        time.Sleep(time.Duration(sleep) * time.Second)
        cursor, err := r.Table("points").Filter(map[string]interface{}{
            "house": house,
        }).Field("points").Sum().Run(rethinkSession)
        if err == io.EOF {
            log.Print("rethink: EOF!")
            sleep += 1 // increase timeout
            cursor.Close()                // <- this is apparently what is panicing...
            continue // try again
        } else if err != nil {
            log.Print(err)
            return 0
        }
        defer cursor.Close() // which in turn is also this in my older function
        if cursor.IsNil() {
            return 0
        }
        var points int
        err = cursor.One(&points)
        if err != nil {
            log.Print(err)
            return 0
        } else {
            return points
        }
    }
}
```

apparently the cursor that is passed back after an EOF is somehow nil and the `cursor.Close()` is causing a `mempanic`

---

confirmed: after removing the cursor.Close() my mempanic went away with it.

**Comment by dancannon** [comment]
@gabeio You should only call `defer cursor.Close()` if there is no error, this is because when a query returns an error no cursor is returned (`nil` is returned). For example your code should instead look like this.

``` go
func getPoints(house string) int {
    sleep := 0
    for {
        time.Sleep(time.Duration(sleep) * time.Second)
        cursor, err := r.Table("points").Filter(map[string]interface{}{
            "house": house,
        }).Field("points").Sum().Run(rethinkSession)
        if err != nil {
            log.Print(err)
            return 0
        }
        defer cursor.Close()
        if cursor.IsNil() {
            return 0
        }
        var points int
        err = cursor.One(&points)
        if err != nil {
            log.Print(err)
            return 0
        } else {
            return points
        }
    }
}
```

**Comment by gabeio** [comment]
I didn't even think about that I thought it would still have a cursor _sigh_.
