### ISSUE TITLE
Changes feed crash

### ISSUE THREAD

**Issue by jpillora** [rethinkdb/rethinkdb-go#287]
See trace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x50b22d]
goroutine 264 [running]:
panic(0xb72040, 0xc820012070)
/usr/local/go/src/runtime/panic.go:464 +0x3e6
  app/vendor/github.com/dancannon/gorethink.(*Connection).read(0xc82037ad20, 0xc82088e060, 0x15, 0x15, 0x15, 0x0, 0x0, 0x0)
/app/vendor/github.com/dancannon/gorethink/connection_helper.go:71 +0xbd
  app/vendor/github.com/dancannon/gorethink.(*Connection).readResponse(0xc82037ad20, 0x0, 0x0, 0x0)
/app/vendor/github.com/dancannon/gorethink/connection.go:232 +0x405
  app/vendor/github.com/dancannon/gorethink.(*Connection).Query(0xc82037ad20, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc8201cc6a0, 0x9f24a0, 0x0, ...)
/app/vendor/github.com/dancannon/gorethink/connection.go:134 +0x2ed
  app/vendor/github.com/dancannon/gorethink.(*Cursor).fetchMore(0xc8204851e0, 0x0, 0x0)
/app/vendor/github.com/dancannon/gorethink/cursor.go:487 +0x139
  app/vendor/github.com/dancannon/gorethink.(*Cursor).nextLocked(0xc8204851e0, 0x9f24a0, 0xc8201cc720, 0xc8201cc720, 0x0, 0x0)
/app/vendor/github.com/dancannon/gorethink/cursor.go:194 +0x112
  app/vendor/github.com/dancannon/gorethink.(*Cursor).Next(0xc8204851e0, 0x9f24a0, 0xc8201cc720, 0x9f24a0)
/app/vendor/github.com/dancannon/gorethink/cursor.go:166 +0x91
  app/vendor/github.com/dancannon/gorethink.(*Cursor).Listen.func1(0xa15540, 0xc8204c1c20, 0xc8204851e0)
/app/vendor/github.com/dancannon/gorethink/cursor.go:421 +0x19d
created by   app/vendor/github.com/dancannon/gorethink.(*Cursor).Listen
/app/vendor/github.com/dancannon/gorethink/cursor.go:430 +0x49
```

This is occurring on a EC2 micro instance soon after running an creating ~8 change listeners in a row - results in a  ~113KB response.

Edit: And here's another:

```
panic: assignment to entry in nil map
goroutine 4441 [running]:
panic(0xa2bde0, 0xc820f43710)
/usr/local/go/src/runtime/panic.go:464 +0x3e6
app/vendor/github.com/dancannon/gorethink.(*Connection).processPartialResponse(0xc8210888c0, 0xc800000002, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc82016fb20, 0x8, 0xc, ...)
app/vendor/github.com/dancannon/gorethink/connection.go:314 +0x3e2
app/vendor/github.com/dancannon/gorethink.(*Connection).processResponse(0xc8210888c0, 0xc800000002, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc82016fb20, 0x0, 0x98, ...)
app/vendor/github.com/dancannon/gorethink/connection.go:259 +0x230
app/vendor/github.com/dancannon/gorethink.(*Connection).Query(0xc8210888c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc822551f20, 0x9f24a0, 0x0, ...)
app/vendor/github.com/dancannon/gorethink/connection.go:141 +0x3b0
app/vendor/github.com/dancannon/gorethink.(*Cursor).fetchMore(0xc820924f20, 0x0, 0x0)
app/vendor/github.com/dancannon/gorethink/cursor.go:487 +0x139
app/vendor/github.com/dancannon/gorethink.(*Cursor).nextLocked(0xc820924f20, 0x9f24a0, 0xc822551f90, 0xc822551f90, 0x0, 0x0)
app/vendor/github.com/dancannon/gorethink/cursor.go:194 +0x112
app/vendor/github.com/dancannon/gorethink.(*Cursor).Next(0xc820924f20, 0x9f24a0, 0xc822551f90, 0x9f24a0)
app/vendor/github.com/dancannon/gorethink/cursor.go:166 +0x91
app/vendor/github.com/dancannon/gorethink.(*Cursor).Listen.func1(0xa15540, 0xc820dbe180, 0xc820924f20)
app/vendor/github.com/dancannon/gorethink/cursor.go:421 +0x19d
created by app/vendor/github.com/dancannon/gorethink.(*Cursor).Listen
app/vendor/github.com/dancannon/gorethink/cursor.go:430 +0x49
```

**Comment by dancannon** [comment]
Would it be possible to see the code you are using that are causing these crashes? Thanks.

**Comment by jpillora** [comment]
I'm doing approximately the below for about 6 different tables, users stream down updates for all their stuff, admins stream down everything.

It seems to only occur when I attach change listeners on everything.

At some point, I will restrict the amount of data admin's receive when we start to accumulate more data, though I thought it'd be okay while 1. there's <1000 entries in total in the DB 2. in our early stages we won't have many users and 3. since it's only admins - the heavy queries will rarely be performed.

``` go
func (s *syncHandler) syncAccounts() error {
    query := r.Table("Account")
    if s.Account.IsAdmin {
        initial := model.Accounts{}
        if err := initial.GetAll(s.Session, query); err != nil {
            return err
        }
        for _, r := range initial {
            s.data.Accounts[r.ID] = r
        }
    } else {
        query = query.Get(s.Account.ID)
    }
    //incremental changes
    curs, err := query.Changes().Run(s)
    if err != nil {
        return err
    }
    changes := make(chan AccountChange)
    curs.Listen(changes)
    go s.syncAccountsChanges(curs, changes)
    return nil
}

type AccountChange struct {
    Old *Account `gorethink:"old_val"`
    New *Account `gorethink:"new_val"`
}

func (s *syncHandler) syncAccountsChanges(curs *r.Cursor, changes <-chan model.AccountChange) {
    defer s.cleanup()
    defer curs.Close()
    for {
        select {
        case <-s.cleanedup:
            return
        case c, ok := <-changes:
            if !ok {
                return
            }
            if c.New != nil {
                s.data.Accounts[c.New.ID] = c.New
            } else if c.Old != nil {
                delete(s.data.Accounts, c.Old.ID)
            }
            s.data.Push()
        }
    }
}
```

**Comment by dancannon** [comment]
I think I found the issue, when the driver closed a connection it set the internal connection to nil (https://github.com/dancannon/gorethink/blob/5ec20c7/connection.go#L85-L88) and if there were any outstanding requests there was a chance that the driver would panic when it tried read the response. This way I was closing the connection was probably incorrect so I have changed how it was implemented.

Could you please try the new implementation by checking out the `develop` branch and see if that fixes your issue, thanks.

**Comment by jpillora** [comment]
Awesome - thanks Dan, back from vacation today so will try tonight

**Comment by jpillora** [comment]
The fix has been in our test environment for a day, will give it another day or so though no crashes so far :)

**Comment by jpillora** [comment]
Still no crashes, I think this fix is good to go :)

**Comment by dancannon** [comment]
Great thanks for testing so thoroughly, I will do a release over the weekend.

**Comment by dancannon** [comment]
The fix has been released to master.
