### ISSUE TITLE
[v2] Non-admin users crash on connecting to the database

### ISSUE THREAD

**Issue by gabeio** [rethinkdb/rethinkdb-go#306]
When I made a new non-admin user ie: `roboto` to be able to access rethink it apparently can not access the `rethinkdb` database, and thusly when `r.DB("rethinkdb").Table("server_status")` is called the app crashes.
## Log:

```
time="2016-04-13T20:41:04-04:00" level=warning msg="Error fetching cluster status: gorethink: Only administrators may access system tables. in: \nr.DB(\"rethinkdb\").Table(\"server_status\")"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4d8721]

goroutine 21 [running]:
panic(0x9a3a00, 0xc82000a140)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
gopkg.in/dancannon/gorethink%2ev2.(*Session).Use(0x0, 0xc82000a07b, 0x3)
        /home/gabeio/go/src/gopkg.in/dancannon/gorethink.v2/session.go:219 +0xc1
main.getRethinkSession(0xc820071020)
        /home/gabeio/3bs/database.go:69 +0x50c
created by main.main
        /home/gabeio/3bs/main.go:60 +0xc3
```
## Connection:

``` go
func getRethinkSession(sessionChan chan *r.Session) {
    var rethinkurl []string
    var rethinkuser string
    var rethinkpass string
    var rethinkdb string
    var err error
    switch {
    // simple
    case os.Getenv("RETHINK") != "":
        rethinkurl = []string{os.Getenv("RETHINK")}
        if len(strings.Split(rethinkurl[0], ";")) > 1 {
            rethinkurl = strings.Split(rethinkurl[0], ";")
        }
        if len(strings.Split(rethinkurl[0], ",")) > 1 {
            rethinkurl = strings.Split(rethinkurl[0], ",")
        }
    // docker
    case os.Getenv("RETHINK_PORT_28015_TCP_ADDR") != "" &&
        os.Getenv("RETHINK_PORT_28015_TCP_PORT") != "":
        rethinkurl = []string{os.Getenv("RETHINK_PORT_28015_TCP_ADDR") + ":" +
            os.Getenv("RETHINK_PORT_28015_TCP_PORT")}
    // default fail
    default:
        log.Fatal("RETHINK Env Undefined")
    }
    if os.Getenv("RETHINK_DB") != "" {
        rethinkdb = os.Getenv("RETHINK_DB")
    } else {
        rethinkdb = "3bs"
    }
    if os.Getenv("RETHINK_USER") != "" {
        rethinkuser = os.Getenv("RETHINK_USER")
    }
    if os.Getenv("RETHINK_PASS") != "" {
        rethinkpass = os.Getenv("RETHINK_PASS")
    }
    session, err := r.Connect(r.ConnectOpts{
        Addresses: rethinkurl,
        Username:  rethinkuser,
        Password:  rethinkpass,
        Database:  rethinkdb,
        MaxIdle:   10,
        MaxOpen:   40,
        // DiscoverHosts: true,
    })
    session.Use(rethinkdb)
    if err != nil {
        log.Fatal(err)
    }
    sessionChan <- session
}
```

**Comment by dancannon** [comment]
Hi, thanks for reporting this issue. 

I think I have a partial fix for this in mind that would cause connections with `DiscoverHosts` disabled however it seems like user/pass authentication is completely incompatible with `DiscoverHosts`.

**Comment by gabeio** [comment]
Well in this instance I actually don't have it enabled because the nodes are running within docker but I need them to see each other on the on the network because they are clustered (`--join`ed) and the application is not being run within docker.

**Comment by VerifiedOrganic** [comment]
Having the exact same issue, I am also running it in docker with `--join`

**Comment by gabeio** [comment]
**TEMP FIX:**
@DefunctExodus currently I got this working again by using the `admin` user.

**Comment by dancannon** [comment]
I have pushed a fix to master, however as mentioned `DiscoverHosts` will still not work due to rethinkdb/rethinkdb#5663. If you are still having issues let me know and I will fix it ASAP.

**Comment by gabeio** [comment]
Looking good to me :+1: thanks!
