### ISSUE TITLE
"panic: runtime error"

### ISSUE THREAD

**Issue by Mobilpadde** [rethinkdb/rethinkdb-go#447]
Hi! 

I'm having a weird issue. Whenever I try to connect to the rethinkdb, I get this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x720a1b]

goroutine 1 [running]:
gitbird/vendor/github.com/GoRethink/gorethink.(*Session).IsConnected(0x0, 0x0)
	/home/avl/Documents/gitbird/server/src/gitbird/vendor/github.com/GoRethink/gorethink/session.go:179 +0x2b
gitbird/vendor/github.com/GoRethink/gorethink.Term.Exec(0x86b401, 0x6, 0x3800000000, 0x0, 0x0, 0xc4201560c0, 0x2, 0x2, 0x0, 0x0, ...)
	/home/avl/Documents/gitbird/server/src/gitbird/vendor/github.com/GoRethink/gorethink/query.go:454 +0xb7
gitbird/db.Db.Save(0x0, 0x81b740, 0xc420162200, 0x86ab2e, 0x3, 0x443f47, 0x0)
	/home/avl/Documents/gitbird/server/src/gitbird/db/save.go:8 +0x176
gitbird/logger.Logger.Log(0x0, 0x86adea, 0x4, 0xc42015a330, 0x2e, 0x0, 0x0, 0x0)
	/home/avl/Documents/gitbird/server/src/gitbird/logger/logger.go:39 +0x15b
gitbird/logger.Logger.Error(0x0, 0x86adea, 0x4, 0x8b7d40, 0xc420144230, 0x0, 0x0, 0x0)
	/home/avl/Documents/gitbird/server/src/gitbird/logger/logger.go:51 +0x128
main.main()
	/home/avl/Documents/gitbird/server/src/gitbird/main.go:105 +0x409
```

Though I cannot figure why, as it's only happening in production. Never locally?

I've printed the error:

```
2018/08/30 21:30:49 &net.OpError{Op:"listen", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc420140900), Err:(*os.SyscallError)(0xc420150440)}
```

Hope you guys can help!

**Comment by Mobilpadde** [comment]
Sorry! Not an issue with this package :flushed:
